[versions]
agp = "8.13.0"
junit = "6.0.1"
kotlin = "2.2.21"
pluginPublish = "2.0.0"
swiftAgp = "0.1.0-alpha"
coreKtx = "1.17.0"
activityCompose = "1.11.0"
composeBom = "2025.10.01"
lifecycleRuntimeKtx = "2.9.4"

[libraries]
agp-gradle = { group = "com.android.tools.build", name = "gradle", version.ref = "agp" }
agp-gradle-api = { group = "com.android.tools.build", name = "gradle-api", version.ref = "agp" }
junit-bom = { group = "org.junit", name = "junit-bom", version.ref = "junit" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter" }
junit-platform = { group = "org.junit.platform", name = "junit-platform-launcher" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-lifecycle-viewmodel-compose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "lifecycleRuntimeKtx" }

[plugins]
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish"}
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin"}
java-gradle-plugin = { id = "org.gradle.java-gradle-plugin"}

android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
swift-android-gradle-plugin = { id = "com.charlesmuchene.swift-android-gradle-plugin", version.ref = "swiftAgp" }